version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=12Password
      - MYSQL_DATABASE=demo
    ports:
      - 3306:3306
    command: --sql_mode='' --max_allowed_packet=32505856

