spring:
  thymeleaf.cache: true
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 12Password
    platform: MYSQL
  jpa:
    properties.hibernate:
      jdbc.lob.non_contextual_creation: true

    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
      show-sql: true